"""PDF layout defects found by reading the rendered pages.

- "Generated by dns-audit.com" on the About page had no colour, so it drew
  near-black on the navy box.
- A check's status column was 1.5in, so "Optional, not set up" and
  "Available, not enabled" wrapped; the title sat about 0.17in right of the
  text under it because the header table was narrower than the frame and
  centred.
- Long tables (DMARC tags, subdomains, vendors, SPF mechanisms, DKIM keys)
  ran onto the next page without their header row.
- The "Optional extras" heading could end a page with its items on the next:
  keepWithNext does not reach into a KeepTogether, so the heading now sits
  inside the first item's.
"""
import os
import sys

import pytest
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import KeepTogether, Paragraph

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import audit_engine  # noqa: E402
import pdf_report  # noqa: E402
from conftest import FakeZone, fake_dns  # noqa: E402
from test_status_semantics import DOMAIN, _zone  # noqa: E402

HEADER_CELLS = {"Tag", "Mechanism", "Selector", "Provider", "Subdomain", "Domain"}


@pytest.fixture(scope="module")
def result():
    zone = _zone(f"v=DMARC1; p=none; rua=mailto:d@{DOMAIN}")
    with fake_dns(zone if isinstance(zone, FakeZone) else FakeZone(zone)):
        return audit_engine.run_full_audit(DOMAIN, dkim_selector="s1", scope="complete")


def _text(flowable):
    return getattr(flowable, "text", "") or ""


def test_brand_title_is_white_on_the_navy_box(result):
    S = pdf_report._styles()
    paras = []

    def walk(f):
        if isinstance(f, Paragraph):
            paras.append(f)
        for cell_row in getattr(f, "_cellvalues", []) or []:
            for cell in cell_row:
                for c in (cell if isinstance(cell, (list, tuple)) else [cell]):
                    walk(c)
    for f in pdf_report._about_page(result, S):
        walk(f)
    [brand] = [p for p in paras if "Generated by dns-audit.com" in _text(p)]
    assert brand.style.textColor == colors.white


@pytest.mark.parametrize("label", ["Optional, not set up", "Available, not enabled", "Pass"])
def test_status_fits_one_line_and_header_spans_the_frame(label):
    S = pdf_report._styles()
    hdr = pdf_report._card_header("MTA-STS", label, pdf_report.NEUTRAL_CLR, S)
    assert hdr.hAlign == "LEFT"
    assert sum(hdr._colWidths) == pytest.approx(pdf_report._FRAME_WIDTH)
    status = hdr._cellvalues[0][1]
    if isinstance(status, (list, tuple)):
        status = status[0]
    status.wrap(2.2 * inch - 6, 1000)
    assert len(status.blPara.lines) == 1


def test_long_tables_repeat_their_header_row(result, monkeypatch):
    made = []
    real_init = pdf_report.Table.__init__

    def recording_init(self, *args, **kwargs):
        real_init(self, *args, **kwargs)
        made.append(self)

    monkeypatch.setattr(pdf_report.Table, "__init__", recording_init)
    pdf_report.generate_pdf(result)
    headed = []
    for t in made:
        first = t._cellvalues[0][0] if t._cellvalues else None
        # ReportLab keeps a cell's flowables in a tuple subclass.
        if isinstance(first, (list, tuple)):
            first = first[0] if first else None
        name = _text(first).replace("<b>", "").replace("</b>", "").strip() if isinstance(first, Paragraph) else ""
        if name in HEADER_CELLS:
            headed.append((name, t.repeatRows))
    assert headed, "no header tables found"
    assert all(rr == 1 for _, rr in headed), headed


def test_optional_extras_heading_travels_with_its_first_item(result):
    S = pdf_report._styles()
    els = pdf_report._roadmap_page(result, S)
    holders = [f for f in els if isinstance(f, KeepTogether)
               and any("Optional extras" in _text(c) for c in f._content)]
    assert holders, "Optional extras heading is not inside a KeepTogether"
    assert "Optional extras" in _text(holders[0]._content[0])
    assert len(holders[0]._content) > 1
    assert not any(isinstance(f, Paragraph) and "Optional extras" in _text(f) for f in els)
